apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongodb-config  # The name of the ConfigMap
immutable: false  # Specifies whether the ConfigMap is immutable (false means it can be changed)
data:
  username: admin1  # The username for the MongoDB instance
  mongodb.conf: |  # The configuration file for MongoDB, written in a multi-line string format
    storage:
      dbPath: /data/db  
    replication:
      replSetName: "rs0"  
