apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-storage  # The name of the StorageClass
provisioner: docker.io/hostpath  # The provisioner plugin that will handle the creation of PersistentVolumes
volumeBindingMode: Immediate  # Specifies that volumes should be bound immediately upon creation
reclaimPolicy: Delete  # The policy for what happens to the volume when the PersistentVolumeClaim is deleted (Delete means the volume will be deleted)
